// <auto-generated />
namespace Panele.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class dbFree : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbFree));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291022452_dbFree"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
